# Generated by Django 4.2.23 on 2025-08-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='rating',
            new_name='rating_stars',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='word',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='keywords',
            field=models.JSONField(default='key'),
        ),
    ]
