# Generated by Django 4.2.23 on 2025-08-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_rating_addproduct_rating_stars_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='rating_stars',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='keywords',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='word',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
